In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_diabetes
df = load_diabetes()
X = df.data
y = df.target

In [3]:
X.shape

(442, 10)

In [4]:
X = X[:,:4]

In [5]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y , test_size=0.2, random_state=1)

#### REMEMBER : Mostly fit_transform is done separately for X_train and y_train because the number of columns in them is different. So, once you used fit_transform for the train same can be used for test so there we will use transform only.

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
y_train = sc.fit_transform(y_train.reshape(-1,1))

In [8]:
y_train

array([[-0.63357135],
       [ 1.35529017],
       [-0.13314813],
       [ 0.46992601],
       [-0.63357135],
       [-0.98001819],
       [-0.15881086],
       [ 0.77787876],
       [-1.31363367],
       [ 0.27745554],
       [ 0.17480462],
       [-0.81321045],
       [-1.46761005],
       [ 0.08498507],
       [-0.67206544],
       [ 0.34161236],
       [-1.08266911],
       [ 1.63758019],
       [ 1.63758019],
       [ 0.77787876],
       [-0.73622226],
       [-0.09465403],
       [ 1.47077245],
       [ 1.22697652],
       [-1.26230821],
       [-0.59507725],
       [ 0.23896145],
       [ 0.1106478 ],
       [-0.24863041],
       [-1.35212777],
       [-0.04332857],
       [-1.1596573 ],
       [ 1.17565107],
       [ 1.07300015],
       [ 0.40576919],
       [-0.2871245 ],
       [-0.12031676],
       [-0.95435546],
       [-0.33844996],
       [ 0.80354149],
       [-0.81321045],
       [ 0.31594964],
       [-0.40260678],
       [-0.78754772],
       [ 1.49643518],
       [ 0

In [9]:
from sklearn.svm import SVR
svr = SVR(kernel='rbf', C=1.0, epsilon=0.5)
svr.fit(x_train, y_train)

c:\Users\SPURUSHO\Downloads\ML_AI\MachineLearningPrac\MLenv\lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(epsilon=0.5)

In [10]:
y_pred = svr.predict(x_test)

In [11]:
y_pred = sc.inverse_transform(y_pred.reshape(-1,1))

In [12]:
y_pred

array([[107.03225478],
       [147.5296688 ],
       [175.48234145],
       [ 92.040305  ],
       [167.47828486],
       [196.78310599],
       [236.5780328 ],
       [133.59412816],
       [128.03928438],
       [106.07471587],
       [156.67949209],
       [128.43536279],
       [121.61438662],
       [ 98.36067061],
       [236.57988785],
       [235.35956951],
       [169.53401472],
       [107.61983919],
       [114.54291327],
       [135.38402813],
       [175.42606601],
       [ 90.41151138],
       [129.01976217],
       [130.83855378],
       [ 89.68327825],
       [224.23400514],
       [122.77080654],
       [170.08571062],
       [112.78892287],
       [192.23361372],
       [117.42364889],
       [106.95666705],
       [132.80450851],
       [122.35830373],
       [ 91.28961078],
       [178.35195457],
       [104.68920115],
       [233.33574299],
       [112.20420045],
       [131.73032957],
       [116.59056753],
       [169.05578264],
       [135.20459064],
       [119

In [14]:
y_test

array([ 78., 152., 200.,  59., 311., 178., 332., 132., 156., 135., 220.,
       233.,  91.,  51., 195., 109., 217.,  94.,  89., 111., 129., 181.,
       168.,  97., 115., 202.,  84., 147., 253., 144., 262., 115.,  68.,
        65., 252., 212., 142., 215., 180., 163., 151., 283.,  66.,  83.,
       214., 189., 302.,  93., 178., 241.,  52., 144., 102., 200., 232.,
        97., 109.,  55.,  63.,  98.,  88., 233., 235.,  97., 243.,  59.,
       138., 220., 137.,  72., 109.,  71.,  74., 219., 196., 170., 199.,
        71., 155.,  52.,  63.,  88.,  97., 100.,  64., 107.,  49.,  60.,
       346.])

In [15]:
y_test = y_test.reshape(-1,1)

In [16]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.22405657317140382

#### See here the problem is choosing of the model and dataset type must match 

In [135]:
df.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']